# Configuration file
# https://github.com/connection-lost/LockettePro/wiki/*-config.yml
# If there are missing entries, you can add them manually.

language-file-name: 'lang.yml'
enable-quick-protect: true
enable-uuid-support: false
block-interfere-placement: true
block-item-transfer-in: false
block-item-transfer-out: true
block-hopper-minecart: remove
cache-time-seconds: 0
private-signs:
- '[Private]'
- '[private]'
additional-signs:
- '[More Users]'
- '[more users]'
everyone-signs:
- '[Everyone]'
- '[everyone]'
timer-signs:
- '[Timer:@]'
- '[timer:@]'
lockables:
- CHEST
- TRAPPED_CHEST
- FURNACE
- BURNING_FURNACE
- HOPPER
- BREWING_STAND
- DIAMOND_BLOCK
- EMERALD_BLOCK
- IRON_BLOCK
- GOLD_BLOCK
- BED
- WOODEN_DOOR
- SPRUCE_DOOR
- BIRCH_DOOR
- JUNGLE_DOOR
- ACACIA_DOOR
- DARK_OAK_DOOR
- IRON_DOOR_BLOCK
- BEACON
- JUKEBOX
- NOTEBLOCK
- TRAPDOOR
- ANVIL
- DISPENSER
- DROPPER
- IRON_TRAPDOOR
- FENCE_GATE
- SPRUCE_FENCE_GATE
- BIRCH_FENCE_GATE
- JUNGLE_FENCE_GATE
- DARK_OAK_FENCE_GATE
- ACACIA_FENCE_GATE
- MOB_SPAWNER
- WHITE_SHULKER_BOX
- ORANGE_SHULKER_BOX
- MAGENTA_SHULKER_BOX
- LIGHT_BLUE_SHULKER_BOX
- YELLOW_SHULKER_BOX
- LIME_SHULKER_BOX
- PINK_SHULKER_BOX
- GRAY_SHULKER_BOX
- SILVER_SHULKER_BOX
- CYAN_SHULKER_BOX
- PURPLE_SHULKER_BOX
- BLUE_SHULKER_BOX
- BROWN_SHULKER_BOX
- GREEN_SHULKER_BOX
- RED_SHULKER_BOX
- BLACK_SHULKER_BOX
- CAUYLDRON
protection-exempt:
- explosion
